# 配置站点
title: '博客名称'
description: '介绍一下'
keyword: '关键词'
url: 'https://你的用户名.github.io' # 修改成你的网址

# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''

# Navigation links 导航链接
nav:
  文章分类: '/tags.html'

# Footer 底栏
footer:
  since: 2023

# Author 配置博主信息
author: '你的名字'
nickname: '你的昵称'
bio: '你的简介'
avatar: '/assets/img/profile.png' # 请把本设置对应的头像换成你的

# Search 搜索
search: true

# Night mode 夜间模式
nightMode: false

# Comments 评论功能
comments:
  giscus: false # 如果需要评论，请打开并按下一行配置
  giscus_script: '请按照 https://giscus.app/zh-CN 的指示得到 script 标签，然后去掉换行放到这里'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share 分享
social-share: false
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# Theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/'
  email: 'mailto:no-reply@example.com'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'Gemfile', 'gulpfile.js', 'LICENSE', 'package.json', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
